{"uuid":"20a27b7d-313c-4069-ba8f-e399381ccacd","historyId":"6727cf18f1ae931fb9b26ec0d9fe1356","fullName":"PersonMapperTest.testInsertPerson","labels":[{"name":"package","value":"PersonMapperTest"},{"name":"testClass","value":"PersonMapperTest"},{"name":"testMethod","value":"testInsertPerson"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"rest-assured-homework"},{"name":"subSuite","value":"PersonMapperTest"},{"name":"host","value":"EJOI-2"},{"name":"thread","value":"21528@EJOI-2.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testInsertPerson","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column \"employee_id\"; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birth_date) VALUES (?, ?, ?, ?, ?, ?, ?) [23502-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Column.validateConvertUpdateSequence(Column.java:365)\r\n\tat org.h2.table.Table.convertInsertRow(Table.java:936)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:167)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:163)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:256)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:413)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n### The error may exist in db/mapper/EmployeeMapper.java (best guess)\r\n### The error may involve db.mapper.EmployeeMapper.insertEmployee-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO employee (name, department, phone, address, salary, email, birth_date) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column \"employee_id\"; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birth_date) VALUES (?, ?, ?, ?, ?, ?, ?) [23502-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Column.validateConvertUpdateSequence(Column.java:365)\r\n\tat org.h2.table.Table.convertInsertRow(Table.java:936)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:167)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:163)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:256)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:413)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n","trace":"org.apache.ibatis.exceptions.PersistenceException: \r\n### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column \"employee_id\"; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birth_date) VALUES (?, ?, ?, ?, ?, ?, ?) [23502-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Column.validateConvertUpdateSequence(Column.java:365)\r\n\tat org.h2.table.Table.convertInsertRow(Table.java:936)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:167)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:163)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:256)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:413)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n### The error may exist in db/mapper/EmployeeMapper.java (best guess)\r\n### The error may involve db.mapper.EmployeeMapper.insertEmployee-Inline\r\n### The error occurred while setting parameters\r\n### SQL: INSERT INTO employee (name, department, phone, address, salary, email, birth_date) VALUES (?, ?, ?, ?, ?, ?, ?)\r\n### Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column \"employee_id\"; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birth_date) VALUES (?, ?, ?, ?, ?, ?, ?) [23502-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Column.validateConvertUpdateSequence(Column.java:365)\r\n\tat org.h2.table.Table.convertInsertRow(Table.java:936)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:167)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:163)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:256)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:413)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n\tat org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)\r\n\tat org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)\r\n\tat org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)\r\n\tat org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)\r\n\tat jdk.proxy2/jdk.proxy2.$Proxy14.insertEmployee(Unknown Source)\r\n\tat PersonMapperTest.testInsertPerson(PersonMapperTest.java:29)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column \"employee_id\"; SQL statement:\nINSERT INTO employee (name, department, phone, address, salary, email, birth_date) VALUES (?, ?, ?, ?, ?, ?, ?) [23502-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.table.Column.validateConvertUpdateSequence(Column.java:365)\r\n\tat org.h2.table.Table.convertInsertRow(Table.java:936)\r\n\tat org.h2.command.dml.Insert.insertRows(Insert.java:167)\r\n\tat org.h2.command.dml.Insert.update(Insert.java:135)\r\n\tat org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)\r\n\tat org.h2.command.CommandContainer.update(CommandContainer.java:163)\r\n\tat org.h2.command.Command.executeUpdate(Command.java:256)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:413)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:520)\r\n\tat org.h2.engine.SessionRemote.readSQLException(SessionRemote.java:663)\r\n\tat org.h2.engine.SessionRemote.readException(SessionRemote.java:646)\r\n\tat org.h2.engine.SessionRemote.done(SessionRemote.java:620)\r\n\tat org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:225)\r\n\tat org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:262)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:58)\r\n\tat jdk.proxy3/jdk.proxy3.$Proxy16.execute(Unknown Source)\r\n\tat org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)\r\n\tat org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:75)\r\n\tat org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)\r\n\tat org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)\r\n\tat org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)\r\n\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)\r\n\t... 31 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1738354584890,"stop":1738354585380}